---
#
# Tasks and roles for all hosts
#
- hosts: all
  become: yes

  tasks:
    - import_role:
        name: system
      tags:
        - system

    - import_role:
        name: geerlingguy.docker
      tags:
        - docker

    - import_role:
        name: system
        tasks_from: docker_mounts.yml
      tags:
        - system
        - docker

    - import_role:
        name: adguard
      tags:
        - adguard

    - import_role:
        name: services
      tags:
        - services

