---
#
# Tasks and roles for all hosts
#
- hosts: all
  become: yes

  roles:
    - name: system
      tags:
        - system

    - name: geerlingguy.docker
      tags:
          - docker

    - name: containers
      tags:
        - containers

