---
#
# Tasks and roles for all hosts
#
- hosts: all
  become: yes

  roles:
    # - role: system
    #   tags:
    #     - system

    # - role: geerlingguy.docker
    #   tags:
    #       - docker

    - name: containers
      tags:
        - containers

