---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
title: {{ homepage.title }}

background: {{ homepage.background_image }}

headerStyle: {{ homepage.header_style }}

target: _self # Possible options include _blank, _self, and _top

layout:
  Media:
    style: row
    columns: 4

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

