---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
{% raw %}
title: {{HOMEPAGE_VAR_TITLE}}

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}
{% endraw %}

layout:
  Media:
    style: row
    columns: 4

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

