---

- name: restart mdns-publisher
  systemd:
    name: mdns-publisher
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true

- name: restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: true
