---

- name: Make sure that the docker compose folder exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ working_dir }}"
    - "{{ working_dir }}/torrents/tv"
    - "{{ working_dir }}/torrents/movies"
    - "{{ working_dir }}/media/tv"
    - "{{ working_dir }}/media/movies"

- name: Create directories
  file:
    path: "{{ working_dir }}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{ role_path }}/templates/"
  when: item.state == 'directory'

- name: create services and docker-compose files
  template:
    src: '{{ item.src }}'
    dest: "{{ working_dir }}/{{ item.path }}"
    mode: '{{ item.mode }}'
    backup: true
  with_filetree: "{{ role_path }}/templates/"
  when: item.state == 'file'

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ working_dir }}"
    remove_orphans: true

