---

- name: Make sure some folder exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ working_dir }}"
    - "{{ working_dir }}/torrents/tv"
    - "{{ working_dir }}/media/tv"
    - "{{ working_dir }}/torrents/movies"
    - "{{ working_dir }}/media/movies"
    - "{{ working_dir }}/torrents/books"
    - "{{ working_dir }}/media/books"
    - "{{ working_dir }}/torrents/audiobooks"
    - "{{ working_dir }}/media/audiobooks"
    - "{{ working_dir }}/media/podcasts"

- name: Create directories
  file:
    path: "{{ working_dir }}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{ role_path }}/templates/"
  when: item.state == 'directory'

- name: put config files
  template:
    src: '{{ item.src }}'
    dest: "{{ working_dir }}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_filetree: "{{ role_path }}/templates/"
  when: item.state == 'file'

- name: create compose file
  copy:
    src: docker-compose.yml
    dest: "{{ working_dir }}/"
    mode: 0644

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ working_dir }}"
    remove_orphans: true
